version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: yamazakimanabu
      POSTGRES_PASSWORD: P@ssword01
      POSTGRES_DB: GO-WEBAPP-DB
    restart: always
    networks:
      - lesson
networks:
  lesson: